title: "Mikhmedâ€™s Notes"
description: "Bayesian ensembling, KD, and other ML things"
theme: minima

# Enable math-friendly markdown
markdown: kramdown
kramdown:
  input: kramdown
  math_engine: mathjax
